spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: bitnami
    requested-heartbeat: 10
    connection-timeout: 2
    # ssl.enabled: true
    publisher-confirm-type: correlated
    publisher-returns: true
    template.mandatory: true

app:
  is-confirm-enabled: true
