spring:
  rabbitmq:
    host: localhost
    port: 5671
    username: user
    password: bitnami
    requested-heartbeat: 10
    connection-timeout: 2
    ssl:
      enabled: true
      validate-server-certificate: false
    publisher-confirm-type: correlated
    publisher-returns: true
    template.mandatory: true

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"

app:
  is-confirm-enabled: true
